# Use light weight image
language: C

notifications:
  email: false

env:
  matrix:
    - EMACS=emacs-24.1
    - EMACS=emacs-24.2
    - EMACS=emacs-24.3
    - EMACS=emacs-24.4
    - EMACS=emacs-24.5
    - EMACS=emacs-25.1

install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq emacs24 2>&1 > /dev/null
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="~/.evm/bin:$PATH"
  - chmod +x ~/.evm/bin/evm
  - ~/.evm/bin/evm install $EMACS 2>&1 > /dev/null
  - ~/.evm/bin/evm use $EMACS
  - FULL_EMACS_PATH="/usr/local/evm/$EMACS/bin/emacs"
  - export EMACS="$FULL_EMACS_PATH"
  - EMACS="$FULL_EMACS_PATH";
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"

script:
  echo $EMACS --version
  cask install
  cask exec ert-runner
