# Use light weight image
language: C

sudo: false

notifications:
  email: false

matrix:
  include:
  - env: EVM_EMACS=emacs-24.1-travis
  - env: EVM_EMACS=emacs-24.2-travis
  - env: EVM_EMACS=emacs-24.3-travis
  - env: EVM_EMACS=emacs-24.4-travis
  - env: EVM_EMACS=emacs-24.5-travis
  - env: EVM_EMACS=emacs-25.1-travis
  allow_failures:
  - env: EVM_EMACS=emacs-24.1-travis
  - env: EVM_EMACS=emacs-24.2-travis
  - env: EVM_EMACS=emacs-24.3-travis

before_install:
  - source ./travis.sh
  - evm install $EVM_EMACS --use --skip > /dev/null 2>&1
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask upgrade-cask
  - cask --debug

script:
  - emacs --version
  - cask exec ert-runner
